### ISSUE TITLE
Support v2 Linter API

### ISSUE THREAD

**Issue by Arcanemagus** [BradCrumb/atom-linter-phpstan#7]
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

**Comment by Arcanemagus** [comment]
@lenton it's likely this is the cause of your issue #6.

**Comment by mallardduck** [comment]
@Arcanemagus Do you still think this is an issue? If so please feel free to open an identical request in my new fork of this package.

A new incarnation of this can be found here: https://atom.io/packages/linter-phpstan
The new repo is at: https://github.com/mallardduck/linter-phpstan

**Comment by mallardduck** [comment]
Actually nevermind!

I didn't realize that I wasn't exactly _feeling_ this issue since I have both atom-ide-ui and linter installed. Interestingly it seems atom-ide-ui was and is able to consume both V1 and V2 messages.

I know this now because after I've applied changes to support Linter V2 my lints are showing up in the Linter window. They are also still showing up in the atom-ide-ui diagnostics though too.

**Comment by BradCrumb** [comment]
@Arcanemagus @mallardduck Sorry for my very late response. I will upgrade the package as soon as possible.

**Comment by BradCrumb** [comment]
@Arcanemagus Just released a new version with a fix for this issue. Credits to @mallardduck .
